config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get "/signup", to: "users#new"
  resources :users, except: [:new]
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete '/logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 6, maximum: 255 }
  validates :description, presence: true, length: { minimum: 6, maximum: 255 }

end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
belongs_to :article
belongs_to :category

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = email.downcase}
  has_many :articles, dependent: :destroy
  validates :username, presence: true,
  uniqueness: { case_sensitive: false },
  length: { minimum: 3, maximum: 25 }
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email, presence: true,
  uniqueness: { case_sensitive: false },
  length: { maximum: 105 },
  format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base



  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show

  end



  def index
    @articles = Article.all
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
     @article=Article.new
  end

  def edit

  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
     if @article.save
       flash[:notice]="Article is created successfully!"
       redirect_to @article
      else

        render 'new'

       flash[:notice]="Article not created!"
    end
  end
  def update

    if @article.update(article_params)
      flash[:notice]="Article updated successfully!"
      redirect_to @article
     else
      render 'edit'

    end
  end
  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article= Article.find(
      params[:id]
      )
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own article"
      redirect_to @article
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new

    @category = Category.new
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def create
      @category = Category.new(category_params)
      if @category.save
      flash[:notice]="Category created successfully"
        redirect_to @category
      else
        render 'new'
      end

  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category name updated successfully"
      redirect_to @category
    else
      render 'edit'
    end
  end


  private
  def category_params
   params.require(:category).permit(:name)
  end
  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to articles_path if logged_in?
  end

  def about

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
   user = User.find_by(email: params[:session][:email].downcase)
   if user && user.authenticate(params[:session][:password])
    session[:user_id] = user.id
    flash[:notice]= "You have logged in successfully"
    redirect_to user_path(user)
    else
      flash.now[:alert]="There is some error in your login"
      render 'new'

   end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:edit, :update, :show, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]


  def new
    @user = User.new
  end
  def show
  @articles = @user.articles
  @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end
  def index
  @users = User.all
  @users = User.paginate(page: params[:page], per_page: 5)
  end

  def create
    @user = User.new(user_params)
    if @user.save
    flash[:notice]="Welcome #{@user.username} to Alpha blog, you are signed up"
    redirect_to articles_path
    else
      render 'new'
    end

  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all associated articles successfully deleted"
    redirect_to articles_path
  end

  def edit

  end
  def update
    if @user.update(user_params)
      flash[:notice]="User successfully updated!"
      redirect_to @user
      else
        render 'edit'
    end

  end


  private
  def user_params
  params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own account"
      redirect_to @user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/views/articles/_article.html.erb
<% @articles.each do |article|  %>
  <div class="row justify-content-md-center">
  <div class="col-8 mt-4">
    <div class="card text-center shadow mb-5 bg-white rounded">
      <div class="card-header font-italic">
      <% if article.user %>

      <%= link_to article.user.username, user_path(article.user) %>
      <% end %>
      <% if article.categories.any? %>
        <div class="mt-2"><%= render article.categories %></div>
      <% end %>
      </div>
      <div class="card-body">
        <h5 class="card-title "><%= link_to article.title, article_path(article), class:"text-success" %></h5>


        <p class="card-text"><%= truncate( article.description , length: 100) %></p>

        <%= link_to "View", article_path(article), class:"btn btn-outline-success" %>

        <% if logged_in? && (article.user == current_user || current_user.admin?) %>

        <%= link_to "Edit", edit_article_path(article), class:"btn btn-outline-info" %>
        <%= button_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>

        <% end %>
      </div>
      <div class="card-footer text-muted">
       <small>Created <%= time_ago_in_words(article.created_at ) %> ago </small>
      </div>
    </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<div class="container">

<%= render "shared/errors",  obj: @article   %>

  <div class="row justify-content-center">
    <div class="col-10">
      <%= form_with(model: @article, class: "article-form shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row mb-4">
          <%= f.label :title, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Enter Title" %>
          </div>
        </div>

        <div class="form-group row mb-4">
          <%= f.label :description, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Enter Description here..." %>
          </div>
        </div>


        <div class="form-group row">
        <%= f.label :category, class: "col-2 col-form-label text-light" %>
        <div class="col-10">
          <%= f.collection_select(:category_ids, Category.all, :id, :name,
          { prompt: "Make your selection from the list below (can be empty)"}, { multiple: true, size: 5, class: "custom-select shadow rounded w-100" }) %>
        </div>
      </div>



        <div class="form-group row justify-content-center">
           <div class="">
              <%= f.submit "Save Article", class:"btn btn-outline-light btn-lg mt-2" %>
          </div>

        </div>
      <% end %>
    </div>

    <%= link_to "Cancel and Back to Articles", articles_path,  class:"text-primary" %>
  </div>
</div>

app/views/articles/edit.html.erb
  <h1 class="mt-4 text-center">Edit Article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="mt-4 text-center">Listing all Articles</h1>
<div class="content" style="padding-bottom: 60px;">

    <div class="flickr_pagination">
      <%= will_paginate @articles, :container => false %>
    </div>
    <%= render 'article' %>
    <div class="flickr_pagination mb-4">
      <%= will_paginate @articles, :container => false %>
    </div>

</div>

app/views/articles/new.html.erb
  <h1 class="mt-4 text-center">Create Article</h1>

    <%= render 'form' %>

app/views/articles/show.html.erb
<h1 class="mt-4 text-center"><%= @article.title %></h1>
<div class="row justify-content-md-center">
  <div class="col-8 mt-4">
    <div class="card text-center shadow mb-5 bg-white rounded">
      <div class="card-header font-italic">
         <%= @article.user.username if @article.user %>

         <% if @article.categories.any? %>
           <div class="mt-2"><%= render @article.categories %></div>
         <% end %>


      </div>
      <div class="card-body">



        <div class="card-text text-left" style="text-align: left;"><%= simple_format(@article.description )%></div>
        <% if logged_in? && (@article.user == current_user || current_user.admin?) %>


        <%= link_to "Edit", edit_article_path(@article), class:"btn btn-outline-info" %>
        <%= button_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
        <% end %>
        <%= link_to "Back to Articles", articles_path, class:"btn btn-outline-primary" %>

      </div>
      <div class="card-footer text-muted">
        <small>Created <%= time_ago_in_words(@article.created_at ) %> ago </small>
      </div>
    </div>
  </div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge rounded-pill bg-info text-dark no-underline mr-1" %>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
<%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
  <div class="form-group row">
    <%= f.label :name, "Category name", class: "col-2 col-form-label text-light" %>
    <div class="col-10">
      <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>
    </div>
  </div>

  <div class="form-group row justify-content-center">
    <div class="col-10 offset-2 mt-3">
      <%= f.submit class: "btn btn-outline-light btn-lg btn-block" %>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Edit category name</h1>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'form' %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to category ]', category_path(@category), class: "text-info" %>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<h1 class="mt-4 text-center">Categories list</h1>
<div class="flickr_pagination">
  <%= will_paginate @categories, :container => false %>
</div>
  <div class="container">

    <% @categories.each do |category|  %>
      <div class="row justify-content-md-center">
      <div class="col-4 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body font-italic">
           <h4 class="card-title"> <%= link_to category.name, category, class: "text-success"  %></h4>
           <p class="card-text"><%= pluralize(category.articles.count, "article") %></p>

          </div>
          <div class="card-footer text-muted">
          <small>Joined <%= time_ago_in_words(category.created_at ) %> ago </small>
          </div>
        </div>
        </div>
      </div>
    <% end %>


  </div>
  <div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
  </div>

app/views/categories/new.html.erb
<h1 class="mt-4 text-center">Create Category</h1>

<div class="container">

<%= render "shared/errors", obj: @category  %>

  <div class="row justify-content-center  ">
    <div class="col-10 ">
    <%= render 'form' %>


    </div>
    <div class="mb-3">
    <%= link_to '[ Cancel and return to categories listing ]', categories_path, class: "text-info" %>
  </div>
  </div>
</div>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>
  <div class="text-center mt-4">
    <%= link_to "Edit category name", edit_category_path(@category), class: "btn btn-outline-info" %>
  </div>
<% end %>

<h3 class="text-center mt-4">Articles</h3>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", media: 'all', "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'shared/header' %>
  <div id="page-content">
    <%= render 'shared/messages' %>

      <%= yield %>
  </div>
  <%= render 'shared/footer' %>

  </body>
</html>

app/views/pages/about.html.erb
<h1>This is About page</h1>
<%= link_to "Articles listing", articles_path %>
<%= link_to "Home page", root_path %>

app/views/pages/home.html.erb
<div id="page-content">
   <div class="container mt-3">
      <div class="jumbotron text-center " >
        <h1 class="display-4">Alpha Blog</h1>
        <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
        <hr class="my-4">
        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        <p class="lead">

          <%= link_to "Sign Up", signup_path, class:"btn btn-success btn-lg" %>
        </p>
      </div>
    </div>

</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show">
    <h2>The following errors are preventing <%= obj.class.name.downcase %> from saving:</h2>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer style="background-color: #333; color: #fff; text-align: center; position: fixed; bottom: 0; width: 100%; z-index: 999;" >
  <p>&copy; 2023 <a href="https://afaqshahidkhan.vercel.app/" class="text-white" target="_blank">AfaqShahidKhan</a></p>
</footer>

app/views/shared/_header.html.erb
<div id="page-content">
      <nav class="navbar navbar-expand-lg bg-body-tertiary ">
      <div class="container-fluid">

        <%= link_to "Afaq's Blog", root_path,class:"navbar-brand" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">

            <li class="nav-item">
              <%= link_to "Bloggers", users_path, class:"nav-link" %>

            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Article Menu
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Create new Article", new_article_path, class:"dropdown-item" %></li>
                  <li><%= link_to "View Articles", articles_path, class:"dropdown-item" %></li>

                </ul>
            </li>





            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Categories
                </a>
                <ul class="dropdown-menu">
                <% if logged_in? && current_user.admin? %>
                  <li> <%= link_to "Create new category", new_category_path, class: "dropdown-item" %></li>
                <% end %>
                <li><%= link_to "View categories", categories_path, class: "dropdown-item" %></li>
                </ul>
            </li>







              <% if logged_in? %>

                <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
                </a>
                <ul class="dropdown-menu">
                <li><%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %></li>
                <li><%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %></li>
                <li><%= button_to "Delete profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure?" } %></li>
                </ul>
            </li>

                <li class="nav-item">
                <%= button_to "Log out",
                logout_path,
                method: :delete, data: { confirm: "Are you sure?" },
                class: "nav-link" %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to 'Log in', login_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to 'Sign up', signup_path, class: "nav-link" %>
                </li>
              <% end %>
          </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
</div>

app/views/shared/_messages.html.erb
<% flash.each do |name, msg| %>


  <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">

  <%= msg %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
  <span aria-hidden="true">&times;</span>
</button>
</div>
<% end %>

app/views/users/_form.html.erb
<div class="container">

<%= render "shared/errors", obj: @user  %>

  <div class="row justify-content-center">
    <div class="col-10">
      <%= form_with(model: @user, class: "user-form shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row mb-3">
          <%= f.label :username, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter username" %>
          </div>
        </div>

        <div class="form-group row mb-3">
          <%= f.label :email, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter email" %>
          </div>
        </div>

        <div class="form-group row mb-3">
          <%= f.label :password, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Make a password" %>
          </div>
       </div>

        <div class="form-group row justify-content-center">
           <div class="">
              <%= f.submit(@user.new_record? ?  "Sign Up" : "Update User", class:"btn btn-outline-light btn-lg mt-2" ) %>
          </div>

        </div>
      <% end %>
    </div>

    <%= link_to "Cancel and Back to users", users_path,  class:"text-primary" %>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="mt-4 text-center">Sign Up for Alpha Blog</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="mt-4 text-center">Sign Up for Alpha Blog</h1>
<div class="flickr_pagination">
  <%= will_paginate @users, :container => false %>
</div>
  <div class="container">

    <% @users.each do |user|  %>
      <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
           <h4> <%= link_to user.username, user  %></h4>
          </div>
          <div class="card-body">


            <%= link_to image_tag("afaqshahid.jpg", alt: user.username, class: "profile-image", width: 100, height: 100), user_path(user) %>


            <%= link_to "View Profile", user_path(user), class:"btn btn-outline-success" %>

            <% if logged_in? %>
              <% if user == current_user %>
                <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-info" %>
            <% end %>
              <% if current_user.admin? %>
                <%= link_to "Delete user", user_path(user), class: "btn btn-outline-danger", method: :delete,
                data: {confirm: "Are you sure you want to delete the user account and all associated articles?"} %>
              <% end %>

        <% end %>

          </div>
          <div class="card-footer text-muted">
          <small>Joined <%= time_ago_in_words(user.created_at ) %> ago </small>
          </div>
        </div>
        </div>
      </div>
    <% end %>


  </div>
  <div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
  </div>

app/views/users/new.html.erb
<h1 class="mt-4 text-center">Sign Up for Alpha Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="mt-4 text-center"><%= @user.username %>'s profile</h1>
<div class="profile-image-container">
  <%= image_tag "afaqshahid.jpg", alt: @user.username, class: "profile-image" %>

</div>

    <% if logged_in? && @user==current_user %>
      <div class="text-center mt-4">
        <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %>
      </div>
    <% end %>
  <h3 class="text-center mt-4">Articles</h3>
  <div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
  </div>
  <%= render 'articles/article' %>
  <div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
  </div>
  </div>